### ISSUE TITLE
landmarker in kyle mouse skeleton do not exist in CAPTURE DEMO SKELETON

### ISSUE THREAD

**Issue by yuan0821** [diegoaldarondo/Label3D#13]
Hi Diego,
Label3D  have a skeleton of Kyle mouse. however, I am not sure how many landmarks it has (). and confused that  the name of kyle mouse model landmarks is different from Jesse's CAPTURE_demo (load_mouse_kyle_anglestruct()). 
### in Label3D mouse22.mat:
{'Tail(end)', 'ElbowR', 'ElbowL' }

### in CAPTURE_demo's load_mouse_kyle_anglestruct() script:
{ForelimbR', 'ForelimbL', HindlimbL', 'HindLimbR'}

May i please ask you to check the landmarker number and name of kyle mouse skeleton? thank you very much for your attention.

**Comment by diegoaldarondo** [comment]
Thanks, I think I just saved the wrong skeleton. 

The skeleton now has the expected 22 points and the correct names.  f880cc2
