### ISSUE TITLE
Load previously saved labels

### ISSUE THREAD

**Issue by davidhildebrand** [diegoaldarondo/Label3D#2]
It does not currently appear to be possible to load previously saved labels to modify them or keep working on the same dataset.  This would be a very helpful feature.  As an interim alternative, it would be nice to have a script that easily combines labels (at least from non-overlapping frame subsets) from multiple save files into a single one.

**Comment by Aquingel** [comment]
Hello, @diegoaldarondo!

I've been having a hard time loading the saved sessions. I found that `loadState` runs while calling `loadAll` and `loadFromState` yields an error: "Cannot access method [method name] in class 'Label3D'."

Moreover, `loadState` overwrites every frame I traverse to. Below is my test run of manual labeling, I labeled the first three frames, and in running `loadState`, it initializes to the first frame and erases all the labels. Moving forward to the second and third frame has the same effect.     
![image](https://github.com/diegoaldarondo/Label3D/assets/91442948/f38879dc-957f-4e61-81ed-387da1ac4087)

Would you help figure out why this happens and how I should go about this?
